services:
# Servicio para PostgreSQL
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image: postgres:14
    container_name: bdd_postgres_db
    restart: always
    env_file:
        - .env
    ports:
      - "127.0.0.1:${POSTGRES_MAPPING}"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

# Servicio para PgAdmin
  pgadmin:
    image: dpage/pgadmin4:7.5
    container_name: bdd_pg_admin
    restart: always
    env_file:
        - .env
    ports:
      - "${PGADMIN_MAPPING}"
